[pytest]
filterwarnings =
    ignore:urllib3 v2 only supports OpenSSL 1\.1\.1\+, currently the 'ssl' module is compiled with 'LibreSSL 2\.8\.3'\.:Warning
    ignore:The 'strip_cdata' option of HTMLParser\(\) has never done anything and will eventually be removed\.:DeprecationWarning:bs4.builder._lxml
